### ISSUE TITLE
Minor UI Changes

### ISSUE THREAD

**Issue by man-git007** [younginnovations/aidstream#308]
Changes to be implemented in AidStream as of 2019-08-13

**TASKS**
- [ ] Fix design of Create an account link in login/register page
- [ ] Click here link not working organization registration page
- [x] Remove organization summary pop up after organization registration
- [x] Remove secondary contact information from administrator account registration
- [ ] Simplification of user profile page.
- [x] Remove account type section from reset password page
- [x] Broken image in organization edit page
- [x] Readonly design implementation in readonly textfields
- [x] Organization secondary contact removal and its dependencies
- [x] Edit link in user listing page
- [x] Add change password link in user profile dropdown
- [x] Allow filter in select option just as select2
- [x] Collapse activity stage in activity page
- [ ] Link no working in import activities page
