### ISSUE TITLE
Implement localization

### ISSUE THREAD

**Issue by RajbanshiNeha** [younginnovations/aidstream#62]
We plan to introduce the localised version of Aidstream in at least one language (probably spanish) to start with.
# Tasks
- [ ] 1. Language selection option.
- [ ] 2. Translation plugin research and implementation.
- [ ] 3. Language should be translated correctly into respective locale.

**Comment by anjesh** [comment]
Localisation module ready for implementation. Language support will be addd as we get the requests and support for language translations.
