### ISSUE TITLE
User Registration

### ISSUE THREAD

**Issue by RajbanshiNeha** [younginnovations/aidstream#65]
We plan to introduce the new registration flow of Aidstream.
# Tasks
- [x] 1. Managed flow of Settings
- [x] 2. Adding registration agency and registration number
- [x] 3. Proper validation 
- [x] 4. Data modifications and migrations
- [x] 5. Integration of email verification for account verification
- [x] 6. Migrations for user permissions
- [x] 7. Added user's secondary contact
